--CUBE_MKT1_MONTH
 SELECT A.OUTLET_PBI, O.NAME, R.NAME REGION, A.YEAR AS TAHUN, A.MONTH BULAN,
    A.SUM_PATIENT AS PATIENT, A.SUM_TEST AS TEST, A.SUM_BRUTO AS BRUTO, A.SUM_DISKON AS DISKON, A.SUM_NETTO AS NETTO , A.SUM_RETUR AS RETUR, A.SUM_TOTAL AS TOTAL,
    DECODE(A.MONTH, 
        '01',T1.M01,
        '02',T1.M02,
        '03',T1.M03,
        '04',T1.M04, 
        '05',T1.M05,
        '06',T1.M06,
        '07',T1.M07,
        '08',T1.M08, 
        '09',T1.M09,
        '10',T1.M10,
        '11',T1.M12,
        '12',T1.M12) TARGET,
        DECODE(A.MONTH, 
        '01',TV1.M01,
        '02',TV1.M02,
        '03',TV1.M03,
        '04',TV1.M04, 
        '05',TV1.M05,
        '06',TV1.M06,
        '07',TV1.M07,
        '08',TV1.M08, 
        '09',TV1.M09,
        '10',TV1.M10,
        '11',TV1.M12,
        '12',TV1.M12) TARGET_VISIT,
        Z.TARGET_LAST, Z.TARGET_VISIT_LAST,
    SUBSTR(A.YEAR+10001,2,4) TAHUN1,SUBSTR(A.YEAR+10002,2,4) TAHUN2,
    SUBSTR(A.YEAR+10003,2,4) TAHUN3,SUBSTR(A.YEAR+10004,2,4) TAHUN4, UPPER(IP.PROVINCE_NAME) PROVINCE_NAME, IC.CITY_NAME
FROM SALES1MONTH_ARIS A,OUTLET_PBI O, TBL_REGION_ERP R,
    OUTLET_PBI_T T1, OUTLET_PBI_TV TV1,
    (SELECT OUTLET_PBI, TO_CHAR(TGL,'YYYY') TAHUN, TO_CHAR(TGL,'MM') BULAN, SUM(TARGET) TARGET_LAST, 
    SUM(TARGET_VISIT) TARGET_VISIT_LAST FROM DAILY_TARGET_ARIS A, UPDATE_DATA_ARIS  B
    WHERE A.TGL < TRUNC(B.LAST_UPDATE)
    AND B.METANAME = 'METAMKT'
    GROUP BY OUTLET_PBI, TO_CHAR(TGL,'YYYY'), TO_CHAR(TGL,'MM')) Z, TBL_OUTLET_LOCATION OL,
    TBL_ID_PROVINCE IP, TBL_ID_CITY IC
WHERE A.OUTLET_PBI = O.OUTLET_PBI(+)
    AND O.REGION_ID = R.PBI_REGION_ID(+)
    AND A.OUTLET_PBI = T1.OUTLET_PBI(+)
    AND A.YEAR = T1.TAHUN(+)
    AND A.OUTLET_PBI = TV1.OUTLET_PBI(+)
    AND A.YEAR = TV1.TAHUN(+)    
    AND A.OUTLET_PBI = Z.OUTLET_PBI(+)
    AND A.YEAR = Z.TAHUN(+)
    AND A.MONTH = Z.BULAN(+)
    AND A.OUTLET_PBI = OL.OUTLET_ID(+)
    AND OL.PROVINCE_ID = IP.PROVINCE_ID(+)
    AND OL.CITY_ID = IC.CITY_ID(+)
    AND TO_NUMBER(A.YEAR) > '2016' -- membuat YEAR TO_number
    AND ROWNUM <=100
   ORDER BY A.OUTLET_PBI, TO_NUMBER(A.YEAR), TO_NUMBER(A.MONTH) ; --membuat YEAR dan MONTH ke NUMBER untuk order



change format With join

 --CUBEMK1_MONTH_ARIS (CHANGE FORMAT JOIN QUERY)ADA KOMEN DALAM SETIAP FIX
 --CREATE OR REPLACE VIEW CUBEMKT1_MONTH_ARIS AS
 SELECT A.OUTLET_PBI, O.NAME, R.NAME AS REGION, A.YEAR AS TAHUN, A.MONTH AS BULAN,
    A.SUM_PATIENT AS PATIENT, A.SUM_TEST AS TEST, A.SUM_BRUTO AS BRUTO, A.SUM_DISKON AS DISKON, A.SUM_NETTO AS NETTO , A.SUM_RETUR AS RETUR, A.SUM_TOTAL AS TOTAL,
    DECODE(A.MONTH, 
        '01',T1.M01,
        '02',T1.M02,
        '03',T1.M03,
        '04',T1.M04, 
        '05',T1.M05,
        '06',T1.M06,
        '07',T1.M07,
        '08',T1.M08, 
        '09',T1.M09,
        '10',T1.M10,
        '11',T1.M11, -- Perbaiki kode untuk bulan November
        '12',T1.M12) TARGET,
    DECODE(A.MONTH, 
        '01',TV1.M01,
        '02',TV1.M02,
        '03',TV1.M03,
        '04',TV1.M04, 
        '05',TV1.M05,
        '06',TV1.M06,
        '07',TV1.M07,
        '08',TV1.M08, 
        '09',TV1.M09,
        '10',TV1.M10,
        '11',TV1.M11, -- Perbaiki kode untuk bulan November
        '12',TV1.M12) TARGET_VISIT,
    Z.TARGET_LAST, Z.TARGET_VISIT_LAST,
    SUBSTR(TO_NUMBER(A.YEAR) + 10001, 2, 4) AS TAHUN1,
    SUBSTR(TO_NUMBER(A.YEAR) + 10002, 2, 4) AS TAHUN2,
    SUBSTR(TO_NUMBER(A.YEAR) + 10003, 2, 4) AS TAHUN3,
    SUBSTR(TO_NUMBER(A.YEAR) + 10004, 2, 4) AS TAHUN4,
    UPPER(IP.PROVINCE_NAME) AS PROVINCE_NAME,
    IC.CITY_NAME
FROM SALES1MONTH_ARIS A
LEFT JOIN OUTLET_PBI O ON A.OUTLET_PBI = O.OUTLET_PBI
LEFT JOIN TBL_REGION_ERP R ON O.REGION_ID = R.PBI_REGION_ID
LEFT JOIN OUTLET_PBI_T T1 ON A.OUTLET_PBI = T1.OUTLET_PBI AND A.YEAR = T1.TAHUN
LEFT JOIN OUTLET_PBI_TV TV1 ON A.OUTLET_PBI = TV1.OUTLET_PBI AND A.YEAR = TV1.TAHUN
LEFT JOIN (
    SELECT OUTLET_PBI, TO_CHAR(TGL, 'YYYY') AS TAHUN, TO_CHAR(TGL, 'MM') AS BULAN,
           SUM(TARGET) AS TARGET_LAST, SUM(TARGET_VISIT) AS TARGET_VISIT_LAST
    FROM DAILY_TARGET_ARIS A
    JOIN UPDATE_DATA_ARIS B ON A.TGL < TRUNC(B.LAST_UPDATE) AND B.METANAME = 'METAMKT'
    GROUP BY OUTLET_PBI, TO_CHAR(TGL, 'YYYY'), TO_CHAR(TGL, 'MM')
) Z ON A.OUTLET_PBI = Z.OUTLET_PBI AND A.YEAR = Z.TAHUN AND A.MONTH = Z.BULAN
LEFT JOIN TBL_OUTLET_LOCATION OL ON A.OUTLET_PBI = OL.OUTLET_ID
LEFT JOIN TBL_ID_PROVINCE IP ON OL.PROVINCE_ID = IP.PROVINCE_ID
LEFT JOIN TBL_ID_CITY IC ON OL.CITY_ID = IC.CITY_ID
WHERE TO_NUMBER(A.YEAR) > 2016 -- Ubah kondisi untuk membandingkan angka
ORDER BY A.OUTLET_PBI, TO_NUMBER(A.YEAR), TO_NUMBER(A.MONTH); -- Ubah A.MONTH menjadi angka sebelum diurutkan